#!/bin/bash

sub_script="condor.sub"

cwd=`pwd -P`
base_dir="$cwd"

#----------------------------------------------------------------------------------------------------

function CheckMultiple()
{
	baseDir="$1"
	
	for mass in ${masses[*]}
	do
		for xangle in ${xangles[*]}
		do
			for period in ${periods[*]}
			do
				tag="$version/$baseDir/m_X_$mass/xangle_$xangle/$period"
				dir="output/$tag"
				eos_dir="/eos/cms/store/group/phys_pps/ppxz/$tag"

				error="n"

				if [ ! -f "$dir/success" ]
				then
					error="y"
				fi

				if [ ! -f "$eos_dir/ntuple.root" ]
				then
					size="0"
				else
					size=$(ls -l "$eos_dir/ntuple.root" |awk '{print $5}')
				fi

				if [ $size -lt 50000000 ]
				then
					error="y"
				fi

				if [ "$error" == "y" ]
				then
					echo "ERROR: $tag"
				fi
			done
		done
	done
}

#----------------------------------------------------------------------------------------------------

version="version4"

masses=(
	800
	1000
	1200
	1400
	1600
)

masses=()
for mass in {780..1650..60}
do
	masses+=($mass)
done

xangles=(
	120
	130
	140
	150
)

periods=(
	"2017_preTS2"
	"2017_postTS2"
)

CheckMultiple "Z"
CheckMultiple "gamma"
