bsub -q 1nd -o dev/null runSimulation.sh 1
bsub -q 1nd -o dev/null runSimulation.sh 2
bsub -q 1nd -o dev/null runSimulation.sh 3
bsub -q 1nd -o dev/null runSimulation.sh 4
bsub -q 1nd -o dev/null runSimulation.sh 5
bsub -q 1nd -o dev/null runSimulation.sh 6
bsub -q 1nd -o dev/null runSimulation.sh 7
bsub -q 1nd -o dev/null runSimulation.sh 8
bsub -q 1nd -o dev/null runSimulation.sh 9
bsub -q 1nd -o dev/null runSimulation.sh 10
